packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@prisma/engines': true
  '@swc/core': true
  esbuild: false
  msgpackr-extract: false
  prisma: true
  prisma-zod-generator: true
  workerd: false
